import Image from "next/image";

interface LogoProps {
  className?: string;
  /**
   * Applies a soft drop-shadow glow behind the mark's actual silhouette
   * (not a bounding box) so it stays legible over a dark or photographic
   * background. This is deliberately a shadow/light effect, not a card —
   * a hard-edged backing plate reads as a pasted-on label rather than a
   * naturally embedded mark. Still the same contrast-guaranteeing
   * technique the Brand Bible names as approved (Section 4.6); it just
   * respects the logo's transparency instead of boxing it.
   */
  onDark?: boolean;
}

/**
 * MBK Holding Commodities logo — full-color lockup only.
 *
 * Per Brand Bible v1.1 (Section 4), this is the ONLY approved logo asset
 * today. Reversed/light, monochrome, and compact marks are explicitly
 * NOT approved and must never be generated by cropping, recoloring, or
 * otherwise deriving from this file — each is a distinct deliverable
 * requiring official MBK approval (see public/brand/logo-primary.png and
 * content/placeholders.ts).
 *
 * There is deliberately no "variant" or "tone" prop: until further
 * versions are approved, every placement uses this same asset.
 */
export function Logo({ className = "", onDark = false }: LogoProps) {
  return (
    <Image
      src="/brand/logo-primary.png"
      alt="MBK Holding Commodities"
      width={810}
      height={342}
      priority
      className={`w-auto ${onDark ? "logo-on-dark" : ""} ${className}`}
    />
  );
}
